### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by DAmNRelentless** [ReSpeak/Qint#1]
I am just interested in what this will be when it's done :)

**Comment by Splamy** [comment]
Simply put, an alternative Teamspeak 3 Client.

**Comment by Bluscream** [comment]
.----------------.  .----------------.  .----------------. 
| .--------------. || .--------------. || .--------------. |
| |     ____     | || | _____  _____ | || |     ____     | |
| |   .'    `.   | || ||_   _||_   _|| || |   .'    `.   | |
| |  /  .--.  \  | || |  | | /\ | |  | || |  /  .--.  \  | |
| |  | |    | |  | || |  | |/  \| |  | || |  | |    | |  | |
| |  \  `--'  /  | || |  |   /\   |  | || |  \  `--'  /  | |
| |   `.____.'   | || |  |__/  \__|  | || |   `.____.'   | |
| |              | || |              | || |              | |
| '--------------' || '--------------' || '--------------' |
 '----------------'  '----------------'  '----------------'

**Comment by DAmNRelentless** [comment]
weebs D:
