### ISSUE TITLE
First message of new clientid is not saved/displayed

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/Qint#13]
`ERRO Failed to write to database, error: FOREIGN KEY constraint failed at proxy/src/db/mod.rs:445`

this also happens with the first server

**Comment by Flakebi** [comment]
Fixed in 071af9234687e9c47cde4ca8b031e066bb8e325e for new servers and in f87994014bb07a2bc76fbf419700680e389f17fc for new clients.
