### ISSUE TITLE
Connection failed cancel button is not always accessale

### ISSUE THREAD

**Issue by Hengoo** [ReSpeak/Qint#21]
When the server name is to long (can easily happen when you directly connect to a channel, since the whole channel tree is in the name) the cancel button is no longer visible.

It would also be great to get more information about why it failed (either in the info tab, or when pressing the "connection failed" box)

**Comment by Flakebi** [comment]
Fixed showing the cancel button with long names.
I’ll close this one and leave #18 open for the error message part, error handling in the frontend is currently missing in general.
