### ISSUE TITLE
Remove Info button when in the options or connection tab

### ISSUE THREAD

**Issue by Hengoo** [ReSpeak/Qint#23]
There is no reason to have this button there, since it only does something for the channel tab.

(and pls fix that the info part doesnt stay open after going to options or connection tab)

**Comment by Flakebi** [comment]
The part that it does not stay open is fixed.

The info button is now not shown, unless the sidebar (with the channel tree) is visible.
Clicking on the info button will show the info tab (and the chat).
Does this solve the issue?
