### ISSUE TITLE
Notifications settings

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/Qint#28]
|                       | TTS | NTFY | ONLY RELEVANT |
|-----------------------|-----|------|----------|
| Poke/Mention          | ☑   | ☑    |          |
| Msg                   | ☑   | ☑    |          |
| Edit Srv/Chan         | ☑   | ☑    | ☑        |
| Client                | ☑   | ☑    | ☑        |
| Client (Switch)       | ☑   | ☑    | ☑        |
| Client (State change) | ☑   | ☑    | ☑        |

- "ONLY RELEVANT": Only actions concernig your Channel/Client

- Ignore all events where invoker == self

**Comment by Flakebi** [comment]
Implemented in ef8c400.

**Comment by Splamy** [comment]
Nice
