### ISSUE TITLE
Minimize to tray: Detect minimize correctly

### ISSUE THREAD

**Issue by TheAsuro** [ReSpeak/Qint#37]
Tauri currently offers no minimize window event. The visibilitychange event in js also doesn't get fired. Currently we can detect it on windows, since it sends a moved event with position (-32000, -32000) but that is obviously terrible and also doesn't work on linux.

- [x] Wait for tauri to implement minimze event
- [ ] Remove windows-specific hack
- [ ] Implement proper minimize to tray

**Comment by Hengoo** [comment]
Improved in https://github.com/ReSpeak/Qint/commit/a2e172f376abebac1a10127f88c7244b69d69206
I don't know if we can actually "remove" the windows hack, but at least Qint does not soft lock any more.
Minimize to tray works in every way we would use it, but has an edge case in the "native" window style
