### ISSUE TITLE
Fix Chat

### ISSUE THREAD

**Issue by Flakebi** [ReSpeak/Qint#7]
- [x] When new messages get appended, the date is inserted two above
- [x] Sometimes, the chat starts at the top (not scrolled down), it should start at the bottom
- [x] When the window is resized, the chat should stay anchored at the bottom

**Comment by Splamy** [comment]
All done with 0d6a415f403880bb056bf9cfdf153e5eb8e7e201 and 0d6a415f403880bb056bf9cfdf153e5eb8e7e201
